server:
  port: 8080
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  datasource:
    url: "jdbc:mysql://localhost:3306/dbname"
    username: "root"
    password: "root"
    driverClassName: "com.mysql.cj.jdbc.Driver"
vaadin:
  servlet:
    productionMode: false
myapp:
  myprop: "value"